[package]
name = "crispy-common"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rp2040-hal = { version = "0.11", features = ["rt", "critical-section-impl"] }
embedded-hal = "1.0.0"
