[package]
name = "crispy-fw-sample"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crispy-common = { path = "../crispy-common" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-probe = { version = "1", features = ["print-defmt"] }
defmt = "1"
defmt-rtt = "1"
